normal kernel

diff --git a/.github/workflows/kernel-neutron.yml b/.github/workflows/kernel-neutron.yml
--- a/.github/workflows/kernel-neutron.yml
+++ b/.github/workflows/kernel-neutron.yml
@@ -1,4 +1,4 @@
-name: Neutron Build GKI Kernel (Sky) with KsuN & SUSFS
+name: Neutron normal arrow
 
 on:
   workflow_dispatch:
@@ -49,7 +49,9 @@ jobs:
       # Clone the kernel repo
       - name: Clone Kernel Source
         run: |
-          git clone --depth=1 -b ${{ env.KERNEL_BRANCH }} ${{ env.KERNEL_SOURCE }} kernel_workspace
+          # git clone --depth=1 -b ${{ env.KERNEL_BRANCH }} ${{ env.KERNEL_SOURCE }} kernel_workspace
+
+          git clone --depth=1 -b lineage-23.2 https://github.com/MrIceT/android_kernel_xiaomi_sky.git kernel_workspace
 
 
       - name: Download Toolchains (Neutron Clang + GCC)
@@ -74,24 +76,24 @@ jobs:
           echo "PATH=$GITHUB_WORKSPACE/toolchain/neutron-clang/bin:$PATH" >> $GITHUB_ENV
 
 
-      - name: Integrate KSU-Next & SUSFS
-        run: |
-          cd $GITHUB_WORKSPACE/kernel_workspace
-          echo "=== 1. Integrating KSU-Next (pershoot dev-susfs) ==="
-          # Execute the setup script directly from pershoot's fork and specify the dev-susfs branch
-          curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s dev
-          
-          echo "=== 2. Cloning SUSFS ==="
-          git clone --depth=1 https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android12-5.10 susfs4ksu
-          
-          echo "=== 3. Patching Main Kernel for SUSFS ==="
-          # Apply the core SUSFS kernel patch
-          patch -p1 < susfs4ksu/kernel_patches/50_add_susfs_in_gki-android12-5.10.patch || true
-          
-          echo "=== 4. Copying SUSFS source files ==="
-          # Copy susfs.c and related header files directly into the kernel tree
-          cp -r susfs4ksu/kernel_patches/fs/* fs/
-          cp -r susfs4ksu/kernel_patches/include/linux/* include/linux/
+      # - name: Integrate KSU-Next & SUSFS
+      #   run: |
+      #     cd $GITHUB_WORKSPACE/kernel_workspace
+      #     echo "=== 1. Integrating KSU-Next (pershoot dev-susfs) ==="
+      #     # Execute the setup script directly from pershoot's fork and specify the dev-susfs branch
+      #     curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s dev
+      #
+      #     echo "=== 2. Cloning SUSFS ==="
+      #     git clone --depth=1 https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android12-5.10 susfs4ksu
+      #
+      #     echo "=== 3. Patching Main Kernel for SUSFS ==="
+      #     # Apply the core SUSFS kernel patch
+      #     patch -p1 < susfs4ksu/kernel_patches/50_add_susfs_in_gki-android12-5.10.patch || true
+      #
+      #     echo "=== 4. Copying SUSFS source files ==="
+      #     # Copy susfs.c and related header files directly into the kernel tree
+      #     cp -r susfs4ksu/kernel_patches/fs/* fs/
+      #     cp -r susfs4ksu/kernel_patches/include/linux/* include/linux/
 
       - name: Compile Kernel (Image)
         run: |
@@ -102,11 +104,9 @@ jobs:
                 CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
                 LLVM=1 LLVM_IAS=1" 
 
-          CUSTOM_NAME="-EndsusKernel"
-         
-          make $ARGS LOCALVERSION=$CUSTOM_NAME ${{ env.DEFCONFIG }}
+          make $ARGS ${{ env.DEFCONFIG }}
           
-          make -j$(nproc --all) $ARGS LOCALVERSION=$CUSTOM_NAME Image
+          make -j$(nproc --all) $ARGS Image
 
 
       - name: Get Build Info (Date & Version)
@@ -120,25 +120,26 @@ jobs:
           # (Make sure the LOCALVERSION matches whatever you used in the compile step!)
           KERNEL_VER=$(make -s O=out ARCH=${{ env.ARCH }}  kernelrelease)
           echo "KERNEL_VER=$KERNEL_VER" >> $GITHUB_ENV
+          mv $GITHUB_WORKSPACE/kernel_workspace/out/arch/arm64/boot/Image $GITHUB_WORKSPACE/kernel_workspace/out/arch/arm64/boot/kernel
 
 
-      - name: Package into AnyKernel3 Flashable ZIP
-        run: |
-          cd $GITHUB_WORKSPACE
-          # cd $GITHUB_WORKSPACE/kernel_workspace
-          # Clone standard AnyKernel3 template
-          git clone --depth=1 https://github.com/osm0sis/AnyKernel3.git anykernel
-          
-          # Copy your freshly compiled Image into the AnyKernel folder
-          cp $GITHUB_WORKSPACE/kernel_workspace/out/arch/arm64/boot/Image anykernel/
-          
-          # Clean up unnecessary placeholders to match the structure you shared
-          rm -f anykernel/README.md
-          
-          # Zip everything up
-          cd anykernel
-          
-          rm -rf .git README.md
+      # - name: Package into AnyKernel3 Flashable ZIP
+      #   run: |
+      #     cd $GITHUB_WORKSPACE
+      #     # cd $GITHUB_WORKSPACE/kernel_workspace
+      #     # Clone standard AnyKernel3 template
+      #     git clone --depth=1 https://github.com/osm0sis/AnyKernel3.git anykernel
+      #
+      #     # Copy your freshly compiled Image into the AnyKernel folder
+      #     cp $GITHUB_WORKSPACE/kernel_workspace/out/arch/arm64/boot/Image anykernel/
+      #
+      #     # Clean up unnecessary placeholders to match the structure you shared
+      #     rm -f anykernel/README.md
+      #
+      #     # Zip everything up
+      #     cd anykernel
+      #
+      #     rm -rf .git README.md
 
       #- name: Setup tmate session for debugging
        # uses: mxschmitt/action-tmate@v3
@@ -147,5 +148,5 @@ jobs:
       - name: Upload Flashable Kernel ZIP
         uses: actions/upload-artifact@v4
         with:
-          name: EndsusKernel-${{ env.KERNEL_VER }}-Sky-KSUN-SuSFS-${{ env.BUILD_DATE }}
-          path: anykernel/
+          name: EndsusKernel-${{ env.KERNEL_VER }}-arrow-${{ env.BUILD_DATE }}
+          path: $GITHUB_WORKSPACE/kernel_workspace/out/arch/arm64/boot/
